version: '3.8'
services:
  client:
    build:
      context: .
      target: client-builder
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app/client
    command: yarn client

  server:
    build:
      context: .
      target: server-builder
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: yarn server

  api:
    build:
      context: .
      target: python-builder
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  python:
    build:
      context: .
      target: python-builder
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: python services/python/main.py

  test:
    build:
      context: .
      target: python-builder
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: pytest
